spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpa_ex?useSSL=false
    username: root
    password: als1347901!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 951589078582-uhucukn4k8ar9evol2mvnps6v31jmo08.apps.googleusercontent.com
            client-secret: 
          facebook:
            client-id: 2246360872313413
            client-secret: 
          github:
            client-id: af219f33074c984f434d
            client-secret: 

custom:
  oauth2:
    kakao:
      client-id: 
